language: ruby
rvm:
  - 2.0.0p481
branches:
  only:
    - master
before_install:
  "rvm_get_stable"

install:
  - "travis_retry bundle install"  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

